CREATE DATABASE PERFUMARIA;

CREATE TABLE PERFUMARIA.PRODUTO (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(100)  NOT NULL,
  MARCA        VARCHAR(100)  NOT NULL,
  DESCRICAO    VARCHAR(1000) NULL,
  PRECO_COMPRA DECIMAL(9,2)  NOT NULL,
  PRECO_VENDA  DECIMAL(9,2)  NOT NULL,
  QUANTIDADE   INT           NOT NULL DEFAULT 0,
  DT_CADASTRO  TIMESTAMP     NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.CATEGORIA (
  ID   INT          NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID),
  CONSTRAINT UC_NOME UNIQUE (NOME)
);

CREATE TABLE PERFUMARIA.PRODUTO_CATEGORIA (
    ID_PRODUTO   BIGINT NOT NULL,
    ID_CATEGORIA INT    NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PERFUMARIA.PRODUTO(ID),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES PERFUMARIA.CATEGORIA(ID)
);

CREATE TABLE PERFUMARIA.CLIENTE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(80),
  BAIRRO VARCHAR(80),
  CIDADE VARCHAR(80),
  ESTADO VARCHAR(2),
  CEP VARCHAR(9),
  SEXO VARCHAR(1),
  TELEFONE VARCHAR(14),
  CELULAR VARCHAR(14),
  CADASTRO TIMESTAMP NOT NULL,  
  ATIVO VARCHAR(1),  
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.FUNCIONARIO (
  ID BIGINT  NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL, 
  CARGO VARCHAR(80) NOT NULL,
  ENDERECO VARCHAR(80),
  BAIRRO VARCHAR(80),
  CIDADE VARCHAR(80),
  ESTADO VARCHAR(2),
  CEP VARCHAR(9),
  SEXO VARCHAR(1),
  TELEFONE VARCHAR(14),
  CELULAR VARCHAR(14),
  CADASTRO TIMESTAMP NOT NULL,
  ATIVO VARCHAR(14),  
  CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.USUARIOS (
	ID BIGINT  NOT NULL AUTO_INCREMENT,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
    LOGIN VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    ATIVO VARCHAR(1)
);

CREATE TABLE PERFUMARIA.FUNCIONARIO_USUARIOS (
    ID_FUNCIONARIO   BIGINT NOT NULL,
    ID_USUARIOS BIGINT NOT NULL,
    CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES PERFUMARIA.FUNCIONARIO(ID),
    CONSTRAINT FK_USUARIOS FOREIGN KEY (ID_USUARIOS) REFERENCES PERFUMARIA.USUARIOS(ID)
);

CREATE TABLE PERFUMARIA.VENDA (
  ID BIGINT  NOT NULL AUTO_INCREMENT,
  CONSTRAINT PK_VENDA PRIMARY KEY (ID),
  ID_CLIENTE BIGINT NOT NULL,
  ID_FUNCIONARIO BIGINT NOT NULL,
  ID_PRODUTO BIGINT NOT NULL,
  QUANTIDADE INT NOT NULL,
  DT_VENDA TIMESTAMP NOT NULL,
  CONSTRAINT FK_VENDA_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PERFUMARIA.CLIENTE(ID),
  CONSTRAINT FK_VENDA_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES PERFUMARIA.FUNCIONARIO(ID),
  CONSTRAINT FK_VENDA_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PERFUMARIA.PRODUTO(ID)
);
INSERT INTO PERFUMARIA.USUARIOS(LOGIN,NOME,SENHA,ATIVO) VALUES ("admin","Administrador","1234","S");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Unisex");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Masculina");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Feminina");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Infantil");
