CREATE DATABASE PERFUMARIA;

CREATE TABLE PERFUMARIA.PRODUTO (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(100)  NOT NULL,
  MARCA        VARCHAR(100)  NOT NULL,
  DESCRICAO    VARCHAR(1000) NULL,
  PRECO_COMPRA DECIMAL(9,2)  NOT NULL,
  PRECO_VENDA  DECIMAL(9,2)  NOT NULL,
  QUANTIDADE   INT           NOT NULL DEFAULT 0,
  DT_CADASTRO  TIMESTAMP     NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.CATEGORIA (
  ID   INT          NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID),
  CONSTRAINT UC_NOME UNIQUE (NOME)
);

CREATE TABLE PERFUMARIA.PRODUTO_CATEGORIA (
    ID_PRODUTO   BIGINT NOT NULL,
    ID_CATEGORIA INT    NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PERFUMARIA.PRODUTO(ID),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES PERFUMARIA.CATEGORIA(ID)
);

CREATE TABLE PERFUMARIA.CLIENTE (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  ENDERECO VARCHAR(30),
  BAIRRO VARCHAR(25),
  CIDADE VARCHAR(20),
  ESTADO VARCHAR(2),
  CEP VARCHAR(8),
  SEXO VARCHAR(1),
  TELEFONE VARCHAR(11),
  CELULAR VARCHAR(11),
  CADASTRO DATE,  
  ATIVO VARCHAR(1),
  DELETADO VARCHAR(1),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.VENDEDOR (
  ID INT  NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,  
  ENDERECO VARCHAR(30),
  BAIRRO VARCHAR(25),
  CIDADE VARCHAR(20),
  ESTADO VARCHAR(2),
  CEP VARCHAR(8),
  SEXO VARCHAR(1),
  TELEFONE VARCHAR(11),
  CELULAR VARCHAR(11),
  CADASTRO DATE,
  ATIVO VARCHAR(1),
  DELETADO VARCHAR(1),
  CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID)
);

CREATE TABLE PERFUMARIA.VENDA (
  ID INT  NOT NULL,
  CONSTRAINT PK_VENDA PRIMARY KEY (ID),
  ID_CLIENTE INT NOT NULL,
  ID_VENDEDOR INT NOT NULL,
  ID_PRODUTO BIGINT NOT NULL,
  QUANTIDADE INT NOT NULL,
  DT_VENDA TIMESTAMP NOT NULL,
  CONSTRAINT FK_VENDA_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PERFUMARIA.CLIENTE(ID),
  CONSTRAINT FK_VENDA_ID_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES PERFUMARIA.VENDEDOR(ID),
  CONSTRAINT FK_VENDA_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PERFUMARIA.PRODUTO(ID)
);

INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Unisex");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Masculina");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Feminina");
INSERT INTO PERFUMARIA.CATEGORIA(NOME) VALUES ("Infantil");
